### ISSUE TITLE
Builds menu blank (empty) since latest updates, kodi Android and Windows x64

### ISSUE THREAD

**Issue by nezzie76** [Zaxxon709/zaxxon#1]
Both Kodi builds are 20.2, on windows x4 and Android 12.

The Build Menu for 7o9 Wizard is now empty.  Not able to apply/install any Builds

**Comment by nezzie76** [comment]
To be more clear, it seems since the latest commits to the Repo.zip, so not a kodi update

**Comment by Zaxxon709** [comment]
I've ended development for my K20 Nexus builds. Going forward all builds are available for K21 Omega only.
