### ISSUE TITLE
Advanced cashe settings

### ISSUE THREAD

**Issue by Arthur1967** [Zaxxon709/zaxxon#2]
I don't use one of your builds, but just recently I can't get your advanced cashe settings to work anymore

**Comment by Arthur1967** [comment]
21.1 Or whatever the latest stable version is

**Comment by Arthur1967** [comment]
It worked fine up until last week

**Comment by Zaxxon709** [comment]
I'm unable to know what the issue is unless you share the settings. 

The presets are available in my wizard. Just install the wizard via my repo and apply the preset suitable for your device.

**Comment by Arthur1967** [comment]
Ok, I will do that.

**Comment by Arthur1967** [comment]
I installed it and I want to use your preset and this is the error it gave me![image](https://github.com/user-attachments/assets/2649ce9c-abea-4939-a027-cdc152842dcd) hopefully that helps

**Comment by Arthur1967** [comment]
I’ll be out tonight, but hopefully that helps you with the issue. I’m
having have a good night.

**Comment by Zaxxon709** [comment]
The issue has been fixed and an update pushed. Install wizard version 99.6.9

**Comment by Arthur1967** [comment]
Awesome, thanks for the update!
